### ISSUE TITLE
In README, expand on how to convert pre/post contracts into type predicates

### ISSUE THREAD

**Issue by ryanberckmans** [plum-umd/rdl#14]
[README: Dependent Types](https://github.com/plum-umd/rdl#dependent-types) has a note that pre/post contracts can be replaced with type predicates.

Using `type` simultaneously with `pre` or `post` results in the error `Inconsistent typecheck flag`, which is OK but means that it's important to understand how to convert any pre/post contract into a type predicate.

This example helped me see that (i) the type nil requires a variable to be valid syntax (follows from nil as alias to NilClass, but tripped me up); and (ii) type variables from anywhere in the signature are available in all predicates:

```
type '(Fixnum x {{ x > 0 }}) -> nil n {{ puts "x #{x}"; x > 50 }}'
def weird(x)
  nil
end
```

**Comment by jeffrey-s-foster** [comment]
Thanks for raising the issue. Not being able to use type and pre/post together was actually a bug (oops!). I just pushed a fix for that. I also added some text to the README about needing a name for dependently typed argument/return positions.

**Comment by ryanberckmans** [comment]
Thanks. I'm enjoying rdl, cool library! Closing this
