### ISSUE TITLE
Problem with mixin types

### ISSUE THREAD

**Issue by j2ren** [plum-umd/rdl#17]
In this example, it is legal for M#bar (through C) to call foo even though M does not have an ancestor that has foo as a method.

module M2
  type :foo ...
  def foo
  end
end

module M
  type :bar ...
  def bar
    foo
  end
end

class C
  include M2
  include M
end

C.new.bar

The current static type checker would set "self" to M when type checking M#bar, which causes a no type error from foo.

**Comment by baban** [comment]
It is resolved dev branch now!
