### ISSUE TITLE
Superclass mismatch for Bignum and Fixnum

### ISSUE THREAD

**Issue by coderanger** [plum-umd/rdl#21]
Ruby 2.4 unified the Bignum and Fixnum classes, the core type defs need an update for this.

**Comment by jeffrey-s-foster** [comment]
Thanks for raising the issue. We've been aware of this for a while but haven't had a chance to fix it. But we now have an approach for fixing it and should do that soon.

**Comment by jeffrey-s-foster** [comment]
This is now fixed in the `dev` branch. We'll put out a new gem soon.
