### ISSUE TITLE
monkey patching not supported yet?

### ISSUE THREAD

**Issue by baban** [plum-umd/rdl#29]
Hi, I'm testing RDL now.
And, I find some problem.

One of those problemns, about monkey patching is not behave like ruby's behavior.

RDL implement check first declared method.
But Ruby is call method last declared method, like a below code.

```ruby
require 'rdl'
require 'types/core'

class Foo
  # thid method declare raise error "error: got type `String' where return type `Fixnum' expected"
  type '(Fixnum) -> String', typecheck: :later
  def foo(num)
    num.to_s
  end
end

class Foo
  # this method declare is not checked by RDL
  type '(String) -> Fixnum', typecheck: :later
  def foo(s)
    s.to_i
  end
end

Foo.new.foo("10")

rdl_do_typecheck :later
```

**Comment by baban** [comment]
Sorry, I notice It is bat case, and so I want to close this issue.
Monkey Patching method should not change return value type.

**Comment by jeffrey-s-foster** [comment]
Sorry for the radio silence on this.

Right, monkey patching a method while changing it's type is going to confuse rdl. It will wind up trying to type check both the old and new method with both the old and new type signature, which isn't going to work. For now I'm going to close this issue as I think that changing a method type like this is probably generally best to avoid, but if there's a good use case for it I'll revisit.
