### ISSUE TITLE
Add repository for type definitions

### ISSUE THREAD

**Issue by stereobooster** [plum-umd/rdl#32]
How about to have repository for type definitions like https://github.com/flowtype/flow-typed

Real world usage: as soon as we get signatures for std lib and [top gems](https://rubygems.org/stats) it can be used for real world projects.

Also: https://github.com/plum-umd/rtc/issues/18

**UPD**: found that there are definitions directly in the project

**Comment by jeffrey-s-foster** [comment]
Sorry for the radio silence on this.

Right, for now the type definitions are just stored in the lib/types directory. If the set of types grows a lot it may be good to factor them out to a different repo in the future. But for now I'm planning to just leave them with the rdl code for simplicity.
