### ISSUE TITLE
Bug: `type_alias': Attempt to redefine type %real (RuntimeError)

### ISSUE THREAD

**Issue by stereobooster** [plum-umd/rdl#33]
```ruby
#!/usr/bin/env ruby
require 'rdl'
require 'types/core'

def nil_echo
  nil.echo
end

RDL.do_typecheck
```

ruby 2.3.3, rdl 2.1.0

```
/2.3.0/gems/rdl-2.1.0/lib/rdl/wrap.rb:515:in `type_alias': Attempt to redefine type %real (RuntimeError)
  from /2.3.0/gems/rdl-2.1.0/lib/types/core/_aliases.rb:5:in `<top (required)>'
  from /2.3.0/gems/rdl-2.1.0/lib/types/core.rb:2:in `require'
  from /2.3.0/gems/rdl-2.1.0/lib/types/core.rb:2:in `block in <top (required)>'
  from /2.3.0/gems/rdl-2.1.0/lib/types/core.rb:2:in `each'
  from /2.3.0/gems/rdl-2.1.0/lib/types/core.rb:2:in `<top (required)>'
  from ./test2.rb:3:in `require'
  from ./test2.rb:3:in `<main>
```

**Comment by stereobooster** [comment]
It was because of `require 'types/core'`

**Comment by stereobooster** [comment]
Will not create an issue for each problem, will just keep posting to this thread.

<details>

<summary> old notes you can skip it </summary>

## 1. ~~Static type checking doesn't work~~

```ruby
#!/usr/bin/env ruby
require 'rdl'
extend RDL::Annotate

type '() -> Integer'
def f
  'haha'
end

RDL.do_typecheck :now
```

This produce no output

```sh
bundle exec  ./test2.rb
```

**UPD** it requires `:now` (or other symbol). 0o

## 2. ~~Installation from git fails~~

Gemfile:
```ruby
# A sample Gemfile
source "https://rubygems.org"

gem "rdl", git: "git@github.com:plum-umd/rdl.git", branch: "dev"
```

```sh
bundle
Updating git@github.com:plum-umd/rdl.git
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Using bundler (1.5.3)
Using ast (2.3.0)
Using parser (2.4.0.0)

NoMethodError: undefined method `spec' for nil:NilClass
Did you mean?  inspect
An error occurred while installing rdl (2.1.0), and Bundler cannot continue.
```

**Solved** by updating bundler to the latest version (bundler 1.15.2)

## 3. How to use static type checker only?

I did something like this, but this looks a bit hacky

```ruby
#!/usr/bin/env ruby

if ARGV.length != 1 then
print "Usage: rdl_static_checker <file>"
  exit 0
end

require 'rdl'

require_relative ARGV[0]

RDL.do_typecheck :now
```

## 4. Which checks are supported

I have set of primitive errors which I want to try to catch with `rdl`. I assume they doesn't work because of lack of signatures or due to point 1

- `"abc".gsub("a", "A", 1)`: ArgumentError: wrong number of arguments (3 for 1..2)
- `"abc" + 1` TypeError: no implicit conversion of Fixnum into String. Expected String, Fixnum given
- `[1,2,3][:a]` TypeError: no implicit conversion of Symbol into Integer. Expected Object, Array given
- `nil.echo` NoMethodError: undefined method 'echo' for nil:NilClass. Expected Object with `echo` method, Nil given
- `{}.fetch(:a)` KeyError: key not found: :a

</details>

**Comment by stereobooster** [comment]
So I managed to run example

### 1. change `core.rb`

```ruby
# require_relative "core/_aliases.rb" # load type aliases first
Dir[File.dirname(__FILE__) + "/core/**/*.rb"].each do |f|
  begin
    require f
  rescue RuntimeError => e
    puts e.message
  end
end
```

### 2. Test script

```ruby
#!/usr/bin/env ruby
require 'rdl'
require 'types/core'

extend RDL::Annotate

type '() -> String', typecheck: :now
def string_int
  "abc" + 1
end

RDL.do_typecheck :now
```

```
Method type:
        (String) -> String
Actual arg type:
      (1)
test2.rb:9:   "abc" + 1
```

### 3. What I expected

I expected it would find error in this script.

```ruby
#!/usr/bin/env ruby
require 'rdl'
require 'types/core'

def string_int
  "abc" + 1
end

RDL.do_typecheck :now
```

 It has all signature of std-lib. **Why it doesn't check it?** What about this `typecheck: :now`, what is it for?

[Flow example for comparison](https://flow.org/try/#0GYVwdgxgLglg9mABAZygJxmA5gfU1ACgEpEBvAKEUTQFMoQ0kAiAQ2QBMnEAqRAJgDciAPTDEAUTRo4aAITkAvuSA)

```js
function string_int() {
  return "asd" * 2; // Error! string. The operand of an arithmetic operation must be a number.
}
```

And [diamondback-ruby example](https://github.com/stereobooster/diamondback-ruby/tree/master/examples#1)

```sh
gem_bin/druby examples/test1.rb
[ERROR] instance Fixnum does not support methods to_str
  in creating instance of Fixnum
  at ./examples/test1.rb:1
  in typing expression 1
  at ./examples/test1.rb:1
  in typing actual argument 1
  at ./examples/test1.rb:1
  in method call %{abc}.+
  at ./examples/test1.rb:1
```

**Comment by jeffrey-s-foster** [comment]
RDL will only type check methods that have type annotations. So in 3 above, since `string_int` doesn't have a type annotation, RDL doesn't try to typecheck the method body.

In 2 above, you don't need the `RDL.do_typecheck :now` line. The `typecheck: :now` argument to `type` indicates that the method body should be checked against the type signature right after the method is defined. This is something that's almost never useful, it's mostly for demos. A more standard use would be `type '() -> String, typecheck: :some_label` and then later calling `RDL.do_typecheck :some_label` to actually typecheck the method against the signature.
