### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by ptarjan** [plum-umd/rdl#40]
I'm a bit worried about this project being unmaintained, given the non-response to my previous issues. I'm going to hold off submitting any more bugs or PRs until I get confirmation. I really hope I get to keep working with RDL, but don't want to go forth with an unmaintained project.

**Comment by jeffrey-s-foster** [comment]
Apologies for the radio silence. I am maintaining the project but have been distracted by other things lately. I will respond to issues within a couple of days.

**Comment by ptarjan** [comment]
That's wonderful news. Do you have a preference for me to submit PRs or issues as I see problems? I have a few obviously bugfix PRs and then a few more questionable ones as well as a few issues I'm unable to solve myself.

**Comment by jeffrey-s-foster** [comment]
Whatever is easiest is fine. I guess for questionable ones it's probably better to discuss first before putting together a PR, but for simple bugfixes the PRs are easy enough.

**Comment by ptarjan** [comment]
(BTW thank you so much for the great project, I'm sorry to have used the nuclear option, I just wanted to know how much support I would have trying to fit this into our huge codebase)
