### ISSUE TITLE
core/types has definitions that don't exist

### ISSUE THREAD

**Issue by ptarjan** [plum-umd/rdl#61]
I went through `core/types` and compared them to the Ruby 2.4.1 stdlib and found 33 definitions that don't have methods.

I did these included before to get the pseudo-stdlib things in scope:

```
require 'abbrev'
require 'benchmark'
require "bigdecimal/math"
require 'coverage'
require 'csv'
require 'date'
require 'uri'
```

And then these don't exist:

```
    "Array.join",
    "Array.member",
    "BasicObject.object_id",
    "[s]Date.now",
    "Enumerator.rewrind",
    "[s]File.readldirpath",
    "File::Stat.pip?",
    "IO.external_enconding",
    "IO.rewrind",
    "IO.write_nonbloc",
    "Module.equal",
    "Module.eql",
    "Numeric.+",
    "Numeric.-",
    "Pathname.symlink",
    "Pathname.readable_real",
    "[s]Process.pgid",
    "[s]Process::Sys.geteid",
    "String.try_convert",
    "String.set_byte",
    "Time.saturday",
    "URI.decode_www_form",
    "URI.decode_www_form_component",
    "URI.encode_www_form",
    "URI.encode_www_form_component",
    "URI.extract",
    "URI.join",
    "URI.parse",
    "URI.regexp",
    "URI.scheme_list",
    "URI.escape",
    "URI.unescape",
    "URI.split",
```

I'd suggest a test that makes sure that the method actually exists on the stdlib when putting a type for it.

**Comment by ainar-g** [comment]
I've looked at some of these. `Array#join` [exists](https://ruby-doc.org/core-2.4.2/Array.html#method-i-join), so your methodology may have errors. `member` must be a misprint of `Array#member?` which comes from `Enumerable` and is an alias for `include?`. `object_id` must be another misprint, because it's defined on `Object`, which is a child of `BasicObject`.

Hopefully, the gem's maintainers will look at this.

**Comment by ptarjan** [comment]
Thanks for pointing out the `Array#join`. I was using ruby 2.2 to test and the annotations are clearly for 2.4.

I do think all the other annotations are just typos of one form or another, they just have to be resolved. A good test to add would be to use reflection to make sure the methods exist as you said they did.

**Comment by mckaz** [comment]
Merged your pull request into dev, to appear in master shortly. Thanks!
