### ISSUE TITLE
#initialize return value is meaningless

### ISSUE THREAD

**Issue by denisdefreyne** [plum-umd/rdl#63]
Suggestion: Remove the requirement that `#initialize` must return `self`.

* * *

The documentation states:

> The return type for `initialize` must always be self or a generic type where the base is self

Yet the return value of `#initialize` is meaningless; it’s virtually never called directly (it is invoked by `.new` usually, which ignores the return value of `#initialize`).

However, RDL _requires_ any `#initialize` functions to return `self`. For example, this will fail:

```ruby
require 'rdl'

class Foo
  extend RDL::Annotate

  type '(String) -> self'
  def initialize(string)
    @string = string
  end
end

Foo.new('asdf')
```

```
Foo#initialize: Return type error. *'s indicate argument lists that matched. (RDL::Type::TypeError)
Method type:
       *(String) -> self
Actual return type:
        String
Actual return value:
        "asdf"
```

One way to fix this is to let `initialize` return `self`:

```
  type '(String) -> self'
  def initialize(string)
    @string = string
    self # <--- ADDED
  end
```

This, however, annoys Rubocop because it knows that returning anything from `#initialize` is meaningless:

```
/Users/denis/Desktop/asdf.rb:9:5: W: self used in void context.
    self
    ^^^^
```

Why does RDL require `#initialize` to return `self`? Can we remove this restriction?

**Comment by jeffrey-s-foster** [comment]
I believe this is fixed in the `dev` branch. Can you try it there and check?
